/**
 * CDN embed delivery utilities.
 * Generates self-executing JS bundles that inject SVG sprites and CSS animations.
 */

interface CdnIcon {
  slug: string;
  svgCode: string;
  animation: string;
  trigger: string;
  duration: number;
}

/**
 * Build a self-executing JavaScript bundle that:
 * 1. Injects an SVG sprite sheet into the DOM using safe DOM methods
 * 2. Replaces <i class="li-custom-{slug}"> elements with SVG + CSS animation
 * 3. Reads data-animation and data-trigger attributes
 *
 * Note: Uses DOMParser for SVG parsing instead of innerHTML to avoid XSS.
 * The SVG content is server-controlled (generated by Recraft and validated
 * by our SVG validator which strips scripts, event handlers, and foreignObject).
 */
export function buildCdnBundle(_userId: string, icons: CdnIcon[]): string {
  const spriteSymbols = icons
    .map((icon) => {
      const inner = extractSvgInner(icon.svgCode);
      const viewBox = extractViewBox(icon.svgCode);
      return `<symbol id="li-${escapeXml(icon.slug)}" viewBox="${escapeXml(viewBox)}">${inner}</symbol>`;
    })
    .join('');

  const cssAnimations = generateCssKeyframes(icons);

  const iconDataJson = JSON.stringify(
    icons.map((i) => ({
      slug: i.slug,
      animation: i.animation,
      trigger: i.trigger,
      duration: i.duration,
    })),
  );

  // Build the sprite SVG as a complete parseable document for DOMParser
  const spriteSvg = `<svg xmlns="http://www.w3.org/2000/svg" style="position:absolute;width:0;height:0;overflow:hidden" aria-hidden="true">${spriteSymbols}</svg>`;

  return `(function(){
  "use strict";

  // Parse and inject SVG sprite sheet using DOMParser (safe, no innerHTML)
  var parser = new DOMParser();
  var spriteDoc = parser.parseFromString(${JSON.stringify(spriteSvg)}, "image/svg+xml");
  var spriteEl = spriteDoc.documentElement;
  if (spriteEl && !spriteDoc.querySelector("parsererror")) {
    document.body.insertBefore(
      document.importNode(spriteEl, true),
      document.body.firstChild
    );
  }

  // Inject CSS animations
  var style = document.createElement("style");
  style.textContent = ${JSON.stringify(cssAnimations)};
  document.head.appendChild(style);

  // Icon data
  var icons = ${iconDataJson};

  // Replace <i class="li-custom-{slug}"> elements with SVG
  function init() {
    icons.forEach(function(iconData) {
      var elements = document.querySelectorAll(".li-custom-" + iconData.slug);
      elements.forEach(function(el) {
        if (el.getAttribute("data-li-rendered")) return;

        var anim = el.getAttribute("data-animation") || iconData.animation;
        var trigger = el.getAttribute("data-trigger") || iconData.trigger;
        var dur = el.getAttribute("data-duration") || iconData.duration;
        var size = el.getAttribute("data-size") || "24";

        var svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
        svg.setAttribute("width", size);
        svg.setAttribute("height", size);
        svg.setAttribute("class", "li-icon li-anim-" + anim);
        svg.style.setProperty("--li-duration", dur + "s");

        var use = document.createElementNS("http://www.w3.org/2000/svg", "use");
        use.setAttributeNS("http://www.w3.org/1999/xlink", "href", "#li-" + iconData.slug);
        svg.appendChild(use);

        if (trigger === "hover") {
          el.addEventListener("mouseenter", function() { svg.classList.add("li-animate"); });
          el.addEventListener("mouseleave", function() { svg.classList.remove("li-animate"); });
        } else if (trigger === "loop") {
          svg.classList.add("li-animate", "li-loop");
        } else if (trigger === "mount") {
          svg.classList.add("li-animate");
        }

        // Clear existing content safely
        while (el.firstChild) { el.removeChild(el.firstChild); }
        el.appendChild(svg);
        el.setAttribute("data-li-rendered", "true");
      });
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
`;
}

function extractSvgInner(svg: string): string {
  const match = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/i);
  return match?.[1]?.trim() ?? '';
}

function extractViewBox(svg: string): string {
  const match = svg.match(/viewBox\s*=\s*"([^"]*)"/);
  return match?.[1] ?? '0 0 24 24';
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function generateCssKeyframes(icons: CdnIcon[]): string {
  const animations = new Set(icons.map((i) => i.animation));
  const keyframes: string[] = [];

  const keyframeMap: Record<string, string> = {
    scale: `@keyframes li-scale{0%,100%{transform:scale(1)}50%{transform:scale(1.2)}}`,
    rotate: `@keyframes li-rotate{0%,100%{transform:rotate(0)}25%{transform:rotate(15deg)}75%{transform:rotate(-15deg)}}`,
    translate: `@keyframes li-translate{0%,100%{transform:translate(0,0)}25%{transform:translate(-2px,-2px)}50%{transform:translate(2px,0)}75%{transform:translate(0,0)}}`,
    shake: `@keyframes li-shake{0%,100%{transform:translateX(0)}20%{transform:translateX(-4px)}40%{transform:translateX(4px)}60%{transform:translateX(-4px)}80%{transform:translateX(4px)}}`,
    pulse: `@keyframes li-pulse{0%,100%{transform:scale(1);opacity:1}50%{transform:scale(1.1);opacity:.8}}`,
    bounce: `@keyframes li-bounce{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}}`,
    spin: `@keyframes li-spin{from{transform:rotate(0)}to{transform:rotate(360deg)}}`,
    heartbeat: `@keyframes li-heartbeat{0%,100%{transform:scale(1)}20%{transform:scale(1.15)}40%{transform:scale(1)}60%{transform:scale(1.1)}}`,
    float: `@keyframes li-float{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}`,
    ring: `@keyframes li-ring{0%,100%{transform:rotate(0)}14%{transform:rotate(15deg)}28%{transform:rotate(-15deg)}42%{transform:rotate(10deg)}57%{transform:rotate(-10deg)}71%{transform:rotate(5deg)}}`,
    wiggle: `@keyframes li-wiggle{0%,100%{transform:rotate(0)}16%{transform:rotate(-8deg)}33%{transform:rotate(8deg)}50%{transform:rotate(-5deg)}66%{transform:rotate(5deg)}}`,
    swing: `@keyframes li-swing{0%,100%{transform:rotate(0)}16%{transform:rotate(12deg)}33%{transform:rotate(-12deg)}50%{transform:rotate(6deg)}66%{transform:rotate(-6deg)}}`,
  };

  for (const anim of animations) {
    if (keyframeMap[anim]) {
      keyframes.push(keyframeMap[anim]);
      keyframes.push(
        `.li-anim-${anim}.li-animate svg,.li-anim-${anim}.li-animate{animation:li-${anim} var(--li-duration,.5s) ease}`,
      );
      keyframes.push(
        `.li-anim-${anim}.li-loop.li-animate svg,.li-anim-${anim}.li-loop.li-animate{animation:li-${anim} var(--li-duration,.5s) ease infinite}`,
      );
    }
  }

  return `.li-icon{display:inline-block;vertical-align:middle;fill:currentColor}\n${keyframes.join('\n')}`;
}
