#!/usr/bin/env node

/**
 * Script to generate TypeScript types for MotionIcons
 *
 * This generates:
 * 1. IconName union type from all icon files
 * 2. IconComponent type for the icon lookup object
 */

import * as fs from 'fs';
import * as path from 'path';

const iconsDir = path.join(__dirname, '..', 'src', 'icons');
const outputFile = path.join(__dirname, '..', 'src', 'lib', 'icon-names.ts');

/**
 * Convert kebab-case to PascalCase
 */
function kebabToPascal(str: string): string {
  return str
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Get all icon files from the icons directory
 */
function getIconFiles(): string[] {
  const files = fs.readdirSync(iconsDir);
  return files
    .filter(file => file.endsWith('.tsx') && file !== 'index.tsx')
    .map(file => file.replace('.tsx', ''))
    .sort();
}

/**
 * Generate the TypeScript file content
 */
function generateTypesContent(iconFiles: string[]): string {
  const iconNames = iconFiles.map(file => kebabToPascal(file));

  const content = `/**
 * Auto-generated icon type definitions
 *
 * DO NOT EDIT MANUALLY - This file is generated by scripts/generate-types.ts
 * Run: pnpm run generate:types
 */

/**
 * Union type of all available icon names (PascalCase)
 *
 * Use this type for type-safe icon references:
 *
 * @example
 * \`\`\`tsx
 * import type { IconName } from 'motionicon';
 *
 * function IconButton({ icon }: { icon: IconName }) {
 *   // Type-safe icon name with autocomplete
 * }
 * \`\`\`
 */
export type IconName =
${iconNames.map(name => `  | '${name}'`).join('\n')};

/**
 * Union type of all available icon names (kebab-case)
 *
 * Useful for configuration objects or CLI tools
 */
export type IconNameKebab =
${iconFiles.map(name => `  | '${name}'`).join('\n')};

/**
 * Array of all icon names (PascalCase)
 *
 * @example
 * \`\`\`tsx
 * import { ICON_NAMES } from 'motionicon';
 *
 * // Iterate over all icons
 * ICON_NAMES.forEach(name => console.log(name));
 * \`\`\`
 */
export const ICON_NAMES = [
${iconNames.map(name => `  '${name}',`).join('\n')}
] as const;

/**
 * Array of all icon names (kebab-case)
 */
export const ICON_NAMES_KEBAB = [
${iconFiles.map(name => `  '${name}',`).join('\n')}
] as const;

/**
 * Total number of icons in the library
 */
export const ICON_COUNT = ${iconNames.length} as const;

/**
 * Mapping from kebab-case to PascalCase names
 */
export const ICON_NAME_MAP: Record<IconNameKebab, IconName> = {
${iconFiles.map(kebab => `  '${kebab}': '${kebabToPascal(kebab)}',`).join('\n')}
};

/**
 * Type guard to check if a string is a valid icon name
 */
export function isIconName(name: string): name is IconName {
  return ICON_NAMES.includes(name as IconName);
}

/**
 * Type guard to check if a string is a valid kebab-case icon name
 */
export function isIconNameKebab(name: string): name is IconNameKebab {
  return ICON_NAMES_KEBAB.includes(name as IconNameKebab);
}
`;

  return content;
}

// Main execution
const iconFiles = getIconFiles();
console.log(`Found ${iconFiles.length} icon files`);

const content = generateTypesContent(iconFiles);
fs.writeFileSync(outputFile, content, 'utf-8');

console.log(`Generated types at: ${outputFile}`);
console.log(`Total icons: ${iconFiles.length}`);
